CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'hyalcink'@'%' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON wordpress.* TO 'hyalcink'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '12345';